import type { AppProps } from 'next/app';
import { GlobalStyles } from '../styles/GlobalStyles';
import { Provider } from 'react-redux';
import Head from 'next/head';
import { wrapper, persistor } from 'store';
import { PersistGate } from 'redux-persist/integration/react';
import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(pageProps);
  return (
    <>
      <Head>
        <title>Hutorok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="korova, na, ochke, natahtari"></meta>
        <link
          rel="shortcut icon"
          href="https://static.tildacdn.com/tild6538-6230-4531-b731-656466393730/favicon_2.ico"
          type="image/x-icon"
        />
      </Head>
      <GlobalStyles />
      <Provider store={store}>
        <PersistGate persistor={persistor} loading={null} />
        <Component {...pageProps} />
      </Provider>
    </>
  );
}

export default MyApp;
