import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import { colors } from 'shared/colors';
import { Layout, PromoCardList } from 'components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hutorok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="korova, na, ochke, natahtari"></meta>
        <link
          rel="shortcut icon"
          href="https://static.tildacdn.com/tild6538-6230-4531-b731-656466393730/favicon_2.ico"
          type="image/x-icon"
        />
      </Head>
      <Layout>
        <Main>
          <H1>Get started with Gscore today!</H1>
          <PromoCardList />
          <ContactContainer>
            <Question>Have more than 10 sites?</Question>
            <ContactLink href="#">Contact us</ContactLink>
          </ContactContainer>
        </Main>
      </Layout>
    </>
  );
};

export default Home;

const H1 = styled.h1`
  font-family: 'THICCCBOI';
  font-style: normal;
  font-weight: 700;
  font-size: 44px;
  line-height: 54px;
  text-align: center;
  color: ${colors.neutral.white};
  padding-bottom: 48.43px;
`;
const Main = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 0;
  gap: 0;
  margin-bottom: 40px;
`;

const ContactContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding-bottom: 42px;
`;
const Question = styled.span`
  font-family: 'THICCCBOI';
  font-style: normal;
  font-weight: 400;
  font-size: 18px;
  line-height: 30px;
  color: ${colors.neutral.white};
`;
const ContactLink = styled.a`
  font-family: 'THICCCBOI';
  font-style: normal;
  font-weight: 400;
  font-size: 18px;
  line-height: 30px;
  text-decoration-line: underline;
  color: ${colors.primary};
`;
