import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import {
  Layout,
  Button,
  ConnectField,
  SubscriptionItem,
  InactiveSubscriptionScreen,
} from 'components';
import styled from 'styled-components';
import { colors } from 'shared/colors';

const Subscriptions: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hutorok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="korova, na, ochke, natahtari"></meta>
        <link
          rel="shortcut icon"
          href="https://static.tildacdn.com/tild6538-6230-4531-b731-656466393730/favicon_2.ico"
          type="image/x-icon"
        />
      </Head>
      <Layout>
        {true ? (
          <Wrapper>
            <Header>
              <Title>My subscriptions</Title>
              <Button UIType="primary" padding="26px 38px">
                Upgrade
              </Button>
            </Header>
            <SubscriptionItem />
            <ConnectField status="Hold" />
            <ConfirmContainer>
              <ButtonLabel>Select the domains you want to keep</ButtonLabel>
              <Button UIType="primary" padding="26px 38px">
                Confirm
              </Button>
            </ConfirmContainer>
          </Wrapper>
        ) : (
          <InactiveSubscriptionScreen />
        )}
      </Layout>
    </>
  );
};

export default Subscriptions;

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  padding: 28px 86px 120px 86px;
  max-width: 1270px;
  margin: 0 auto;
`;

const Header = styled.div`
  display: flex;
  justify-content: space-between;
  margin-bottom: 44px;
`;

const Title = styled.h1`
  font-family: 'THICCCBOI';
  font-style: normal;
  font-weight: 700;
  font-size: 54px;
  line-height: 64px;
  color: ${colors.neutral.white};
`;

const ConfirmContainer = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 48px;
`;

const ButtonLabel = styled.p`
  font-family: 'THICCCBOI';
  font-style: normal;
  font-weight: 700;
  font-size: 20px;
  line-height: 22px;
  color: ${colors.neutral.white};
`;
